---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-ip
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /mnt/data/php-ip

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-ip-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
