---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-06-11T03:34:34Z"
  labels:
    app: php-ip-v3-pod
  name: php-ip-v3-pod
spec:
  ports:
  - name: "8080"
    nodePort: 30221
    port: 8080
    targetPort: 8080
  selector:
    app: php-ip-v3-pod
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-06-11T03:34:34Z"
  labels:
    app: php-ip-v3-pod
  name: php-ip-v3-pod-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: php-ip-v3-pod
  template:
    metadata:
      creationTimestamp: "2024-06-11T03:34:34Z"
      labels:
        app: php-ip-v3-pod
      name: php-ip-v3-pod
    spec:
      containers:
      - image: 192.168.10.250:5000/tang/php-ip:v3
        name: php-ip-v3
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
